services:
    david63.userdefaults.listener:
        class: david63\userdefaults\event\listener
        arguments:
            - '@config'
        tags:
            - { name: event.listener }

    david63.userdefaults.admin.controller:
        class: david63\userdefaults\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@log'
            - '@language'
            - '@dbal.conn'
